import os

def generate_report(violations: dict, rules: dict, output_dir: str):
    """
    Generate static analysis violation report.

    Parameters
    ----------
    violations : dict
        Runtime violation database generated by checker engine.

    rules : dict
        Rule configuration database loaded from rules.json.

    output_dir : str
        Output directory used to store generated report.

    Returns
    -------
    None

    Notes
    -----
    - Report is generated in plain text format.
    - Console output and file output are synchronized.
    - Each rule violation is grouped by:
        1. Rule ID
        2. File name
        3. Violated lines
    """

    # Create output directory if not existing
    os.makedirs(output_dir, exist_ok=True)

    # Final report path
    report_file = os.path.join(output_dir, "report.log")

    # Generate report file
    with open(report_file, "w", encoding="utf-8") as f:
        # Iterate through all violated rules
        for rule_id, violation_data in violations.items():
            # Get rule metadata from rules database
            rule_info = rules.get(rule_id, {})

            description = rule_info.get("description", "No description")
            severity = rule_info.get("severity", "UNKNOWN")
            status = rule_info.get("status", "UNKNOWN")

            # Generate rule header section
            header = (
                f"{rule_id}: {description}\n"
                + "-" * 80
                + "\n"
            )
            print(header)

            # Write to report file
            f.write(header)

            # Track total violations count
            total = 0

            # Iterate through violated files
            for relative_path, lines in violation_data["files"].items():
                # File section header
                file_header = f"\nFile : {relative_path}\n\n"
                print(file_header)
                f.write(file_header)

                # Iterate through violated lines
                for line_no, code in lines:
                    message = (f"Line {line_no:<5}: {code}\n")
                    print(message, end="")
                    f.write(message)
                    total += 1

            # Generate footer summary
            footer = (
                "\n"
                + "-" * 80
                + "\n"
                + f"Total Violations : {total}\n"
                + f"Severity         : {severity}\n"
                + f"Status           : {status}\n"
                + "\n\n"
            )

            print(footer)
            f.write(footer)

    # Final report generation message
    print(f"Report generated: {report_file}")
